FROM nginx
USER root
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./miniServer.c ./home/miniServer.c
COPY ./entrypoint.sh ./home/entrypoint.sh
RUN apt-get update; \
    apt-get install -y spawn-fcgi gcc libfcgi-dev
WORKDIR /home/
RUN chmod +x /home/entrypoint.sh
CMD ["/home/entrypoint.sh"]
